version: '3.8'

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sql_threads
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=XinhIT@30052003
    ports:
      - '1433:1433'
    mem_limit: 2g # Giúp container chạy ổn định hơn trên Mac Air

  api:
    build:
      context: ./Packages/Backend
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=InteractHubDB;User Id=sa;Password=XinhIT@30052003;TrustServerCertificate=True;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  frontend:
    build:
      context: ./Packages/Frontend
      dockerfile: Dockerfile
    ports:
      - '3000:5173' # Sửa thành 3000:5173 nếu dùng Vite
    depends_on:
      - api
