// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(TiktokdbContext))]
    [Migration("20260407160417_InitialTiktokDb")]
    partial class InitialTiktokDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AccountId")
                        .HasName("PK__Account__349DA5A60A9E773E");

                    b.HasIndex("UserId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("ToVideoId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK__Comment__C3B4DFCA67E6451A");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("ToVideoId");

                    b.HasIndex(new[] { "CommentId" }, "UQ__Comment__C3B4DFCB928A9202")
                        .IsUnique();

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RelationshipFromUserToUser", b =>
                {
                    b.Property<int>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelationshipId"));

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("FOLLOWER");

                    b.HasKey("RelationshipId")
                        .HasName("PK__Relation__31FEB881450CA443");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("RelationshipFromUserToUser", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Description")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C713CF253");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Backend.Models.UserCommentLike", b =>
                {
                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("CommentId", "UserId")
                        .HasName("PK__UserComm__12CC530E3B975D49");

                    b.ToTable("UserCommentLike", (string)null);
                });

            modelBuilder.Entity("Backend.Models.UserVideoLike", b =>
                {
                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("VideoId", "UserId")
                        .HasName("PK__UserVide__6B9D9EAE2FB88AEB");

                    b.HasIndex("UserId");

                    b.ToTable("UserVideoLike", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("VideoId")
                        .HasName("PK__Video__BAE5126A3FB86A88");

                    b.HasIndex("UserId");

                    b.ToTable("Video", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Account", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Account__UserId__49C3F6B7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.HasOne("Backend.Models.User", "FromUser")
                        .WithMany("Comments")
                        .HasForeignKey("FromUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Comment__FromUse__4D94879B");

                    b.HasOne("Backend.Models.Comment", "ParentComment")
                        .WithMany("InverseParentComment")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("FK__Comment__ParentC__4E88ABD4");

                    b.HasOne("Backend.Models.Video", "ToVideo")
                        .WithMany("Comments")
                        .HasForeignKey("ToVideoId")
                        .IsRequired()
                        .HasConstraintName("FK__Comment__ToVideo__4F7CD00D");

                    b.Navigation("FromUser");

                    b.Navigation("ParentComment");

                    b.Navigation("ToVideo");
                });

            modelBuilder.Entity("Backend.Models.RelationshipFromUserToUser", b =>
                {
                    b.HasOne("Backend.Models.User", "FromUser")
                        .WithMany("RelationshipFromUserToUserFromUsers")
                        .HasForeignKey("FromUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Relations__FromU__4BAC3F29");

                    b.HasOne("Backend.Models.User", "ToUser")
                        .WithMany("RelationshipFromUserToUserToUsers")
                        .HasForeignKey("ToUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Relations__ToUse__4CA06362");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Backend.Models.UserVideoLike", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("UserVideoLikes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserVideo__UserI__5070F446");

                    b.HasOne("Backend.Models.Video", "Video")
                        .WithMany("UserVideoLikes")
                        .HasForeignKey("VideoId")
                        .IsRequired()
                        .HasConstraintName("FK__UserVideo__Video__5165187F");

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Backend.Models.Video", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Videos")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Video__UserId__4AB81AF0");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.Navigation("InverseParentComment");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Comments");

                    b.Navigation("RelationshipFromUserToUserFromUsers");

                    b.Navigation("RelationshipFromUserToUserToUsers");

                    b.Navigation("UserVideoLikes");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Backend.Models.Video", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("UserVideoLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
